### ISSUE TITLE
could not find 'from zhon import zhuyin'

### ISSUE THREAD

**Issue by Michael1S** [HappyBall/tacotron#1]
Sry,I could not find 'from zhon import zhuyin' in file 'hyperparams.py'.Could u request this question? Anyway,thx.

**Comment by HappyBall** [comment]
Should've installed python package zhon first.
I'll add it in the prerequisites.
Thanks for reminding.

**Comment by Michael1S** [comment]
Thank u for your replying.

I used pinyin not bopomofo，and comment the question like this "# from zhon
import zhuyin".However, I need some new questions...

Chi-Yu Yang <notifications@github.com> 于2018年8月2日周四 下午3:42写道：

**Comment by Michael1S** [comment]
mede some new questions not need....

陈晨毅 <lebhoryi@gmail.com> 于2018年8月2日周四 下午3:48写道：

**Comment by HappyBall** [comment]
Could you tell me what new questions you encounter?
If the input_mode is set to pinyin, should've installed pypinyin package first.
I had added all python packages which will be used in this project in the prerequisites.
Thanks!

**Comment by Lebhoryi** [comment]
Adding packages is really cool！Maybe my question is missing some
packages，now I try again.

Chi-Yu Yang <notifications@github.com>于2018年8月2日 周四16:01写道：

**Comment by Lebhoryi** [comment]
emmmmmm
some other question，could it be used on the product？
My boss didnot like kedaxunfei’ tts,and let me do something in TTS. But I
am just one person and a student🤦‍♂️🤦‍♂️🤦‍♂️😭😭😭even could not say no
to my boss.

陈晨毅 <lebhoryi@gmail.com>于2018年8月2日 周四16:04写道：

**Comment by Lebhoryi** [comment]
Now,it is running.So amazing～

**Comment by HappyBall** [comment]
That's nice!

**Comment by Lebhoryi** [comment]
yeah .Thank u😃😃👏

Chi-Yu Yang <notifications@github.com>于2018年8月2日 周四17:13写道：
